version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
    overwrite: yes
permissions:
  - object: /home/ubuntu/app/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 120
      runas: ubuntu
