export const initialData = [
  {
    rank: 1,
    correctAnswerPercentage: 95,
    name: 'User1',
    university: 0,
  },
  {
    rank: 2,
    correctAnswerPercentage: 90,
    name: 'User2',
    university: 1,
  },
  {
    rank: 3,
    correctAnswerPercentage: 85,
    name: '토키파이팅',
    university: 0,
  },
  {
    rank: 4,
    correctAnswerPercentage: 80,
    name: 'User4',
    university: 1,
  },
  {
    rank: 5,
    correctAnswerPercentage: 75,
    name: 'User5',
    university: 0,
  },
  {
    rank: 6,
    correctAnswerPercentage: 70,
    name: 'User6',
    university: 1,
  },
  {
    rank: 7,
    correctAnswerPercentage: 65,
    name: 'User7',
    university: 0,
  },
  {
    rank: 8,
    correctAnswerPercentage: 60,
    name: 'User8',
    university: 1,
  },
  {
    rank: 9,
    correctAnswerPercentage: 55,
    name: 'User9',
    university: 0,
  },
  {
    rank: 10,
    correctAnswerPercentage: 50,
    name: 'User10',
    university: 1,
  },
  {
    rank: 11,
    correctAnswerPercentage: 45,
    name: 'User11',
    university: 0,
  },
  {
    rank: 12,
    correctAnswerPercentage: 40,
    name: 'User12',
    university: 1,
  },
];

export const additionalData1 = [
  {
    rank: 13,
    correctAnswerPercentage: 35,
    name: 'User13',
    university: 0,
  },
  {
    rank: 14,
    correctAnswerPercentage: 30,
    name: 'User14',
    university: 1,
  },
  {
    rank: 15,
    correctAnswerPercentage: 25,
    name: 'User15',
    university: 0,
  },
  {
    rank: 16,
    correctAnswerPercentage: 20,
    name: 'User16',
    university: 1,
  },
  {
    rank: 17,
    correctAnswerPercentage: 15,
    name: 'User17',
    university: 0,
  },
  {
    rank: 18,
    correctAnswerPercentage: 10,
    name: 'User18',
    university: 1,
  },
  {
    rank: 19,
    correctAnswerPercentage: 5,
    name: 'User19',
    university: 0,
  },
  {
    rank: 20,
    correctAnswerPercentage: 0,
    name: 'User20',
    university: 1,
  },
];
export const additionalData2 = [
  {
    rank: 21,
    correctAnswerPercentage: 95,
    name: 'User21',
    university: 0,
  },
  {
    rank: 22,
    correctAnswerPercentage: 90,
    name: 'User22',
    university: 1,
  },
  {
    rank: 23,
    correctAnswerPercentage: 85,
    name: 'User23',
    university: 0,
  },
  {
    rank: 24,
    correctAnswerPercentage: 80,
    name: 'User24',
    university: 1,
  },
  {
    rank: 25,
    correctAnswerPercentage: 75,
    name: 'User25',
    university: 0,
  },
  {
    rank: 26,
    correctAnswerPercentage: 70,
    name: 'User26',
    university: 1,
  },
  {
    rank: 27,
    correctAnswerPercentage: 65,
    name: 'User27',
    university: 0,
  },
  {
    rank: 28,
    correctAnswerPercentage: 60,
    name: 'User28',
    university: 1,
  },
  {
    rank: 29,
    correctAnswerPercentage: 55,
    name: 'User29',
    university: 0,
  },
  {
    rank: 30,
    correctAnswerPercentage: 50,
    name: 'User30',
    university: 1,
  },
  {
    rank: 31,
    correctAnswerPercentage: 45,
    name: 'User31',
    university: 0,
  },
  {
    rank: 32,
    correctAnswerPercentage: 40,
    name: 'User32',
    university: 1,
  },
  {
    rank: 33,
    correctAnswerPercentage: 35,
    name: 'User33',
    university: 0,
  },
  {
    rank: 34,
    correctAnswerPercentage: 30,
    name: 'User34',
    university: 1,
  },
  {
    rank: 35,
    correctAnswerPercentage: 25,
    name: 'User35',
    university: 0,
  },
  {
    rank: 36,
    correctAnswerPercentage: 20,
    name: 'User36',
    university: 1,
  },
];
