import type { Metadata } from 'next';
import './globals.css';
import StyledComponentsRegistry from '@/libs/design-system/styled-components/registry';
import ThemeClient from '@/libs/design-system/styled-components/ThemeClient';
import { OverlayProvider } from '@/libs/design-system/overlay';
import QueryProvider from '@/libs/client/QueryProvider';
import { AuthProvider } from '@/libs/client/AuthProvider';

export const metadata: Metadata = {
  title: '신나는 정기전 승부예측, TOKY',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <meta httpEquiv="Permissions-Policy" content="web-share=(self)" />
      <body>
        <StyledComponentsRegistry>
          <ThemeClient>
            <QueryProvider>
              <OverlayProvider>
                <AuthProvider />
                <main>{children}</main>
              </OverlayProvider>
            </QueryProvider>
          </ThemeClient>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
