import { PlayerCardProps } from '@/components/PlayerCard';

export const PLAYER_CARD_LIST: PlayerCardProps[] = [
  {
    image: 'https://placehold.co/110',
    name: '이상호',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '이상호',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '이상호',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '이상호',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
  {
    image: 'https://placehold.co/110',
    name: '안세용',
    jerseyNumber: '1',
    position: '투수',
    year: '3학년',
    heightWeight: '180/80',
  },
];
