import { PlayerCardProps } from '@/components/PlayerCard';
import { SelectionType } from '@/libs/constants/sports';

type PlaySports = Exclude<SelectionType, 'all' | 'rugby'>;

type PlayerCardListProps = {
  [key in PlaySports]: PlayerCardProps[];
};
export const BANNER_INFO = {
  all: '/total_banner.webp',
  baseball: '/baseball_banner.webp',
  basketball: '/basketball_banner.webp',
  icehockey: '/icehockey_banner.webp',
  football: '/football_banner.webp',
};

export const KOREA_PLAYER_CARD_LIST: PlayerCardListProps = {
  baseball: [
    {
      image: '/image-proxy/analyze/profile/korea/baseball/21_kimbeomjin.png',
      name: '김범진',
      jerseyNumber: '47',
      position: '내야수',
      year: '21학번',
      heightWeight: '182/86',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/21_parkgeonwoo.png',
      name: '박건우',
      jerseyNumber: '25',
      position: '포수',
      year: '21학번',
      heightWeight: '185/90',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/21_parkchanjin.png',
      name: '박찬진',
      jerseyNumber: '2',
      position: '외야수',
      year: '21학번',
      heightWeight: '170/77',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/21_seojoonwoo.png',
      name: '서준우',
      jerseyNumber: '18',
      position: '투수',
      year: '21학번',
      heightWeight: '181/86',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/21_ohdongeun.png',
      name: '오동운',
      jerseyNumber: '9',
      position: '외야수',
      year: '21학번',
      heightWeight: '175/74',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/21_jogyutaek.png',
      name: '조규택',
      jerseyNumber: '7',
      position: '내야수',
      year: '21학번',
      heightWeight: '178/80',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/21_chaseongyoon.png',
      name: '차성윤',
      jerseyNumber: '17',
      position: '외야수',
      year: '21학번',
      heightWeight: '184/84',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/22_parksehoon.png',
      name: '박세훈',
      jerseyNumber: '11',
      position: '외야수',
      year: '22학번',
      heightWeight: '191/91',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/22_anminseong.png',
      name: '안민성',
      jerseyNumber: '12',
      position: '포수',
      year: '22학번',
      heightWeight: '183/92',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/22_anjaeyeon.png',
      name: '안재연',
      jerseyNumber: '16',
      position: '내야수',
      year: '22학번',
      heightWeight: '177/80',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/22_ryujeongtaek.png',
      name: '유정택',
      jerseyNumber: '3',
      position: '외야수',
      year: '22학번',
      heightWeight: '170/70',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/22_leegeonho.png',
      name: '이건호',
      jerseyNumber: '19',
      position: '투수',
      year: '22학번',
      heightWeight: '175/76',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/22_jeongteunteun.png',
      name: '정튼튼',
      jerseyNumber: '21',
      position: '투수',
      year: '22학번',
      heightWeight: '180/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_gangminwoo.png',
      name: '강민우',
      jerseyNumber: '10',
      position: '내야수',
      year: '23학번',
      heightWeight: '173/76',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_kimdaehong.png',
      name: '김대홍',
      jerseyNumber: '22',
      position: '포수',
      year: '23학번',
      heightWeight: '177/82',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_kimdonghwan.png',
      name: '김동환',
      jerseyNumber: '54',
      position: '투수',
      year: '23학번',
      heightWeight: '182/80',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_kimbeomguen.png',
      name: '김범근',
      jerseyNumber: '56',
      position: '투수',
      year: '23학번',
      heightWeight: '181/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_kimjoonyeob.png',
      name: '김준엽',
      jerseyNumber: '52',
      position: '내야수',
      year: '23학번',
      heightWeight: '177/86',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_kimyounghoo.png',
      name: '김영후',
      jerseyNumber: '53',
      position: '외야수',
      year: '23학번',
      heightWeight: '182/75',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_jeongeunjin.png',
      name: '정원진',
      jerseyNumber: '28',
      position: '투수',
      year: '23학번',
      heightWeight: '181/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/23_hongeunseok.png',
      name: '홍은성',
      jerseyNumber: '51',
      position: '투수',
      year: '23학번',
      heightWeight: '178/79',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_gangchaeeun.png',
      name: '강채운',
      jerseyNumber: '37',
      position: '투수',
      year: '24학번',
      heightWeight: '191/95',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_gongminseo.png',
      name: '공민서',
      jerseyNumber: '8',
      position: '외야수',
      year: '24학번',
      heightWeight: '178/80',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_kimjaeik.png',
      name: '김재익',
      jerseyNumber: '6',
      position: '내야수',
      year: '24학번',
      heightWeight: '181/81',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_parkjiheok.png',
      name: '박지혁',
      jerseyNumber: '27',
      position: '포수',
      year: '24학번',
      heightWeight: '180/88',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_yujaedong.png',
      name: '유재동',
      jerseyNumber: '41',
      position: '투수',
      year: '24학번',
      heightWeight: '184/80',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_jinhyeonjae.png',
      name: '진현제',
      jerseyNumber: '15',
      position: '내야수',
      year: '24학번',
      heightWeight: '182/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_hangyuhyeok.png',
      name: '한규혁',
      jerseyNumber: '23',
      position: '내야수',
      year: '24학번',
      heightWeight: '192/94',
    },
    {
      image: '/image-proxy/analyze/profile/korea/baseball/24_hongjuhwan.png',
      name: '홍주환',
      jerseyNumber: '31',
      position: '투수',
      year: '24학번',
      heightWeight: '175/68',
    },
  ],
  basketball: [
    {
      image: '/image-proxy/analyze/profile/korea/basketball/21_kimtaehoon.png',
      name: '김태훈',
      jerseyNumber: '9',
      position: 'F',
      year: '21학번',
      heightWeight: '190/86',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/21_yangjoon.png',
      name: '양준',
      jerseyNumber: '11',
      position: 'C',
      year: '21학번',
      heightWeight: '202/96',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/21_parkjoonhyoung.png',
      name: '박준형',
      jerseyNumber: '13',
      position: 'F',
      year: '21학번',
      heightWeight: '192/89',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/21_kimdoeun.png',
      name: '김도은',
      jerseyNumber: '5',
      position: 'G',
      year: '21학번',
      heightWeight: '183/86',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/22_parkjeonhwan.png',
      name: '박정환',
      jerseyNumber: '6',
      position: 'G',
      year: '22학번',
      heightWeight: '181/76',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/22_kimmingyu.png',
      name: '김민규',
      jerseyNumber: '23',
      position: 'F',
      year: '22학번',
      heightWeight: '196/88',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/22_leegeonhee.png',
      name: '이건희',
      jerseyNumber: '0',
      position: 'G',
      year: '22학번',
      heightWeight: '187/80',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/23_moonyouhyeon.png',
      name: '문유현',
      jerseyNumber: '24',
      position: 'G',
      year: '23학번',
      heightWeight: '181/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/23_leedongguen.png',
      name: '이동근',
      jerseyNumber: '3',
      position: 'F',
      year: '23학번',
      heightWeight: '197/95',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/23_yoongichan.png',
      name: '윤기찬',
      jerseyNumber: '10',
      position: 'F',
      year: '23학번',
      heightWeight: '194/91',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/23_leejaemin.png',
      name: '이재민',
      jerseyNumber: '12',
      position: 'C',
      year: '23학번',
      heightWeight: '198/105',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/23_youminsoo.png',
      name: '유민수',
      jerseyNumber: '1',
      position: 'F',
      year: '23학번',
      heightWeight: '201/94',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/24_seokjoonhwee.png',
      name: '석준휘',
      jerseyNumber: '7',
      position: 'G',
      year: '24학번',
      heightWeight: '191/83',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/24_kimjeonghyeondaniel.png',
      name: '김정현다니엘',
      jerseyNumber: '15',
      position: 'F',
      year: '24학번',
      heightWeight: '194/92',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/24_jeonseungwon.png',
      name: '정승원',
      jerseyNumber: '21',
      position: 'C',
      year: '24학번',
      heightWeight: '195/87',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/24_simjooeon.png',
      name: '심주언',
      jerseyNumber: '2',
      position: 'F',
      year: '24학번',
      heightWeight: '190/84',
    },
    {
      image: '/image-proxy/analyze/profile/korea/basketball/24_leedoyoun.png',
      name: '이도윤',
      jerseyNumber: '14',
      position: 'C',
      year: '24학번',
      heightWeight: '200/102',
    },
  ],
  icehockey: [
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/21_leeyounseok.png',
      name: '이윤석',
      jerseyNumber: '72',
      position: 'FW',
      year: '21학번',
      heightWeight: '184/85',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/21_gwonminjae.png',
      name: '권민재',
      jerseyNumber: '50',
      position: 'DF',
      year: '21학번',
      heightWeight: '183/77',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/21_kimhyeonseo.png',
      name: '김현서',
      jerseyNumber: '56',
      position: 'DF',
      year: '21학번',
      heightWeight: '183/80',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/21_songeunseok.png',
      name: '송은석',
      jerseyNumber: '37',
      position: 'GK',
      year: '21학번',
      heightWeight: '180/86',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/21_jangheegon.png',
      name: '장희곤',
      jerseyNumber: '78',
      position: 'FW',
      year: '21학번',
      heightWeight: '178/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/21_kimdongjoon.png',
      name: '김동준',
      jerseyNumber: '87',
      position: 'FW',
      year: '21학번',
      heightWeight: '178/75',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/22_gwonhyeonsoo.png',
      name: '권현수',
      jerseyNumber: '70',
      position: 'FW',
      year: '22학번',
      heightWeight: '178/74',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/22_kimmooseong.png',
      name: '김무성',
      jerseyNumber: '13',
      position: 'FW',
      year: '22학번',
      heightWeight: '178/74',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/22_leejoonseo.png',
      name: '이준서',
      jerseyNumber: '14',
      position: 'FW',
      year: '22학번',
      heightWeight: '180/73',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/22_yangjeongwon.png',
      name: '양정원',
      jerseyNumber: '89',
      position: 'DF',
      year: '22학번',
      heightWeight: '177/74',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/22_johyeongyeom.png',
      name: '조현겸',
      jerseyNumber: '7',
      position: 'DF',
      year: '22학번',
      heightWeight: '178/74',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/23_leemooyoung.png',
      name: '이무영',
      jerseyNumber: '79',
      position: 'FW',
      year: '23학번',
      heightWeight: '175/73',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/23_choiseongsoon.png',
      name: '최성순',
      jerseyNumber: '44',
      position: 'FW',
      year: '23학번',
      heightWeight: '176/76',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/23_heominjoon.png',
      name: '허민준',
      jerseyNumber: '17',
      position: 'FW',
      year: '23학번',
      heightWeight: '185/83',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/23_kimseongho.png',
      name: '김성호',
      jerseyNumber: '43',
      position: 'DF',
      year: '23학번',
      heightWeight: '182/75',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/23_moonseungmin.png',
      name: '문승민',
      jerseyNumber: '33',
      position: 'DF',
      year: '23학번',
      heightWeight: '184/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/23_seominkyung.png',
      name: '서경민',
      jerseyNumber: '31',
      position: 'G',
      year: '23학번',
      heightWeight: '175/70',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_parkminchae.png',
      name: '박민채',
      jerseyNumber: '20',
      position: 'FW',
      year: '24학번',
      heightWeight: '180/88',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_sonhyeon.png',
      name: '손현',
      jerseyNumber: '29',
      position: 'FW',
      year: '24학번',
      heightWeight: '175/73',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_leejihoon.png',
      name: '이지훈',
      jerseyNumber: '75',
      position: 'FW',
      year: '24학번',
      heightWeight: '175/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_jungyoungguen.png',
      name: '정영근',
      jerseyNumber: '10',
      position: 'FW',
      year: '24학번',
      heightWeight: '175/70',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_parktaeyoung.png',
      name: '박태영',
      jerseyNumber: '82',
      position: 'DF',
      year: '24학번',
      heightWeight: '180/82',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_songjoonseob.png',
      name: '송준섭',
      jerseyNumber: '5',
      position: 'DF',
      year: '24학번',
      heightWeight: '187/83',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_yangtaegyu.png',
      name: '양태규',
      jerseyNumber: '97',
      position: 'DF',
      year: '24학번',
      heightWeight: '180/75',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/24_choiwonhyoung.png',
      name: '최원형',
      jerseyNumber: '21',
      position: 'DF',
      year: '24학번',
      heightWeight: '173/73',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/20_jeonjonghoon.png',
      name: '전종훈',
      jerseyNumber: '32',
      position: 'G',
      year: '20학번',
      heightWeight: '-',
    },
    {
      image: '/image-proxy/analyze/profile/korea/icehockey/23_kimsangyeob.png',
      name: '김상엽',
      jerseyNumber: '91',
      position: 'FW',
      year: '23학번',
      heightWeight: '-',
    },
  ],
  football: [
    {
      image: '/image-proxy/analyze/profile/korea/football/21_bangwoojin.png',
      name: '방우진',
      jerseyNumber: '4',
      position: 'DF',
      year: '21학번',
      heightWeight: '186/79',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/21_cheonseyoon.png',
      name: '천세윤',
      jerseyNumber: '6',
      position: 'MF',
      year: '21학번',
      heightWeight: '170/68',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/21_kimchaewoong.png',
      name: '김채웅',
      jerseyNumber: '7',
      position: 'FW',
      year: '21학번',
      heightWeight: '177/74',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/21_leejiho.png',
      name: '이지호',
      jerseyNumber: '10',
      position: 'FW',
      year: '21학번',
      heightWeight: '183/74',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/21_kimgihyeon.png',
      name: '김기현',
      jerseyNumber: '11',
      position: 'FW',
      year: '21학번',
      heightWeight: '186/79',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/21_youkyoungmin.png',
      name: '유경민',
      jerseyNumber: '12',
      position: 'FW',
      year: '21학번',
      heightWeight: '172/65',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/22_jeongjooseon.png',
      name: '정주선',
      jerseyNumber: '5',
      position: 'DF',
      year: '22학번',
      heightWeight: '190/86',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/22_dongjaemin.png',
      name: '동재민',
      jerseyNumber: '8',
      position: 'MF',
      year: '22학번',
      heightWeight: '181/72',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/22_gangminjoon.png',
      name: '강민준',
      jerseyNumber: '13',
      position: 'DF',
      year: '22학번',
      heightWeight: '171/64',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/22_choihyeonseung.png',
      name: '최현승',
      jerseyNumber: '14',
      position: 'DF',
      year: '22학번',
      heightWeight: '177/75',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/22_sinseungmin.png',
      name: '신승민',
      jerseyNumber: '18',
      position: 'DF',
      year: '22학번',
      heightWeight: '178/71',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/22_gwonyongseung.png',
      name: '권용승',
      jerseyNumber: '20',
      position: 'DF',
      year: '22학번',
      heightWeight: '185/82',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_kimjeonghoon.png',
      name: '김정훈',
      jerseyNumber: '1',
      position: 'GK',
      year: '23학번',
      heightWeight: '188/81',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_songjoonhwee.png',
      name: '송준휘',
      jerseyNumber: '3',
      position: 'DF',
      year: '23학번',
      heightWeight: '186/81',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_kimjiwon.png',
      name: '김지원',
      jerseyNumber: '9',
      position: 'FW',
      year: '23학번',
      heightWeight: '189/87',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_parkchani.png',
      name: '박찬이',
      jerseyNumber: '16',
      position: 'MF',
      year: '23학번',
      heightWeight: '179/70',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_leeyouho.png',
      name: '이유호',
      jerseyNumber: '22',
      position: 'MF',
      year: '23학번',
      heightWeight: '179/73',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_yangjiseob.png',
      name: '양지섭',
      jerseyNumber: '23',
      position: 'DF',
      year: '23학번',
      heightWeight: '171/71',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_jeonguiheon.png',
      name: '정의헌',
      jerseyNumber: '24',
      position: 'DF',
      year: '23학번',
      heightWeight: '176/68',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_kimminhyeok.png',
      name: '김민혁',
      jerseyNumber: '25',
      position: 'DF',
      year: '23학번',
      heightWeight: '182/73',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/23_joyeseong.png',
      name: '조예성',
      jerseyNumber: '26',
      position: 'DF',
      year: '23학번',
      heightWeight: '184/78',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_pyeonbijang.png',
      name: '편비장',
      jerseyNumber: '21',
      position: 'GK',
      year: '24학번',
      heightWeight: '194/84',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_yoosiwoo.png',
      name: '유시우',
      jerseyNumber: '29',
      position: 'DF',
      year: '24학번',
      heightWeight: '183/72',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_gangchansol.png',
      name: '강찬솔',
      jerseyNumber: '2',
      position: 'DF',
      year: '24학번',
      heightWeight: '184/82',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_chasoohyeon.png',
      name: '차수현',
      jerseyNumber: '30',
      position: 'DF',
      year: '24학번',
      heightWeight: '188/90',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_kimjeontaesoo.png',
      name: '김관우',
      jerseyNumber: '33',
      position: 'MF',
      year: '24학번',
      heightWeight: '190/83',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_kimjeontaesoo.png',
      name: '김전태수',
      jerseyNumber: '15',
      position: 'MF',
      year: '24학번',
      heightWeight: '178/70',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_parkminjoon.png',
      name: '박민준',
      jerseyNumber: '28',
      position: 'MF',
      year: '24학번',
      heightWeight: '175/73',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_kimminseok.png',
      name: '김민석',
      jerseyNumber: '19',
      position: 'FW',
      year: '24학번',
      heightWeight: '179/72',
    },
    {
      image: '/image-proxy/analyze/profile/korea/football/24_shinyeongjoon.png',
      name: '신영준',
      jerseyNumber: '27',
      position: 'FW',
      year: '24학번',
      heightWeight: '173/68',
    },
  ],
};

export const YONSEI_PLAYER_CARD_LIST: PlayerCardListProps = {
  baseball: [
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/20_seongjoonhwan.png',
      name: '성준한',
      jerseyNumber: '17',
      position: '외야수',
      year: '20학번',
      heightWeight: '175/72',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/21_nabyeonhoon.png',
      name: '나병훈',
      jerseyNumber: '11',
      position: '투수',
      year: '21학번',
      heightWeight: '181/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/21_kimjinhyeong.png',
      name: '김진형',
      jerseyNumber: '7',
      position: '외야수',
      year: '21학번',
      heightWeight: '175/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/21_leedongjin.png',
      name: '이동준',
      jerseyNumber: '1',
      position: '내야수',
      year: '21학번',
      heightWeight: '174/72',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/21_leewoojin.png',
      name: '이우진',
      jerseyNumber: '10',
      position: '포수',
      year: '21학번',
      heightWeight: '180/95',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/22_yangseojoon.png',
      name: '양서준',
      jerseyNumber: '23',
      position: '내야수',
      year: '22학번',
      heightWeight: '176/74',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/22_leegeonhee.png',
      name: '이건희',
      jerseyNumber: '4',
      position: '포수',
      year: '22학번',
      heightWeight: '176/85',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/22_gwonwoojae.png',
      name: '권우재',
      jerseyNumber: '13',
      position: '내야수',
      year: '22학번',
      heightWeight: '180/93',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/22_leechanyoung.png',
      name: '이찬영',
      jerseyNumber: '51',
      position: '투수',
      year: '22학번',
      heightWeight: '178/77',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/22_yoonseonghwan.png',
      name: '윤성환',
      jerseyNumber: '41',
      position: '투수',
      year: '22학번',
      heightWeight: '185/90',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/22_umjimin.png',
      name: '엄지민',
      jerseyNumber: '21',
      position: '투수',
      year: '22학번',
      heightWeight: '182/76',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/23_gangmingoo.png',
      name: '강민구',
      jerseyNumber: '47',
      position: '투수',
      year: '23학번',
      heightWeight: '180/85',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/23_kimdongjoo.png',
      name: '김동주',
      jerseyNumber: '22',
      position: '포수',
      year: '23학번',
      heightWeight: '179/84',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/23_kimtaeyang.png',
      name: '김태양',
      jerseyNumber: '18',
      position: '투수',
      year: '23학번',
      heightWeight: '178/82',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/23_leejiwon.png',
      name: '이지원',
      jerseyNumber: '5',
      position: '내야수',
      year: '23학번',
      heightWeight: '180/77',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/23_joyoungwoo.png',
      name: '조영우',
      jerseyNumber: '19',
      position: '투수',
      year: '23학번',
      heightWeight: '182/81',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/23_jojanghyeon.png',
      name: '조장현',
      jerseyNumber: '53',
      position: '외야수',
      year: '23학번',
      heightWeight: '178/77',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/23_hongseoyeon.png',
      name: '홍서연',
      jerseyNumber: '16',
      position: '내야수',
      year: '23학번',
      heightWeight: '183/88',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_gongdohyeok.png',
      name: '공도혁',
      jerseyNumber: '8',
      position: '내야수',
      year: '24학번',
      heightWeight: '185/80',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_kimgeonwoo.png',
      name: '김건우',
      jerseyNumber: '12',
      position: '포수',
      year: '24학번',
      heightWeight: '177/86',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_kiminwoo.png',
      name: '김인우',
      jerseyNumber: '40',
      position: '투수',
      year: '24학번',
      heightWeight: '182/93',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_kimtaehyeon.png',
      name: '김태현',
      jerseyNumber: '24',
      position: '내야수',
      year: '24학번',
      heightWeight: '176/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_seonghyeonho.png',
      name: '성현호',
      jerseyNumber: '31',
      position: '외야수',
      year: '24학번',
      heightWeight: '176/72',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_leejongho.png',
      name: '이종호',
      jerseyNumber: '30',
      position: '투수',
      year: '24학번',
      heightWeight: '184/88',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_leechoongheon.png',
      name: '이충헌',
      jerseyNumber: '50',
      position: '외야수',
      year: '24학번',
      heightWeight: '180/80',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/baseball/24_hongyounjae.png',
      name: '홍윤재',
      jerseyNumber: '20',
      position: '투수',
      year: '24학번',
      heightWeight: '180/80',
    },
  ],
  basketball: [
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/21_gangjaemin.png',
      name: '강재민',
      jerseyNumber: '3',
      position: 'F',
      year: '21학번',
      heightWeight: '195/80',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/21_choihyeongchan.png',
      name: '최형찬',
      jerseyNumber: '17',
      position: 'G',
      year: '21학번',
      heightWeight: '189/84',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/22_kimbobae.png',
      name: '김보배',
      jerseyNumber: '2',
      position: 'F/C',
      year: '22학번',
      heightWeight: '203/96',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/22_leeminseo.png',
      name: '이민서',
      jerseyNumber: '1',
      position: 'G',
      year: '22학번',
      heightWeight: '181/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/22_leegyutae.png',
      name: '이규태',
      jerseyNumber: '23',
      position: 'F/C',
      year: '22학번',
      heightWeight: '199/95',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/22_anseongwoo.png',
      name: '안성우',
      jerseyNumber: '11',
      position: 'G',
      year: '22학번',
      heightWeight: '184/82',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/23_gangjihoon.png',
      name: '강지훈',
      jerseyNumber: '13',
      position: 'C',
      year: '23학번',
      heightWeight: '202/96',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/23_leejooyoung.png',
      name: '이주영',
      jerseyNumber: '5',
      position: 'G',
      year: '23학번',
      heightWeight: '189/82',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/23_leechaeyoung.png',
      name: '이채형',
      jerseyNumber: '7',
      position: 'G',
      year: '23학번',
      heightWeight: '187/80',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/23_leehaesol.png',
      name: '이해솔',
      jerseyNumber: '4',
      position: 'F',
      year: '23학번',
      heightWeight: '189/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/23_hongsangmin.png',
      name: '홍상민',
      jerseyNumber: '10',
      position: 'F/C',
      year: '23학번',
      heightWeight: '200/100',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/24_gangtaehyeon.png',
      name: '강태현',
      jerseyNumber: '0',
      position: 'G',
      year: '24학번',
      heightWeight: '197/86',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/24_gilsangchan.png',
      name: '길상찬',
      jerseyNumber: '22',
      position: 'F/C',
      year: '24학번',
      heightWeight: '195/90',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/24_kimseungwoo.png',
      name: '김승우',
      jerseyNumber: '6',
      position: 'F',
      year: '24학번',
      heightWeight: '192/84',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/basketball/24_leeyoujin.png',
      name: '이유진',
      jerseyNumber: '9',
      position: 'F',
      year: '24학번',
      heightWeight: '199/84',
    },
  ],
  icehockey: [
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/21_youtaewoong.png',
      name: '유태웅',
      jerseyNumber: '81',
      position: 'DF(주장)',
      year: '21학번',
      heightWeight: '180/76',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/21_parkjoonseo.png',
      name: '박준서',
      jerseyNumber: '43',
      position: 'DF',
      year: '21학번',
      heightWeight: '180/74',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/21_parksangjin.png',
      name: '박상진',
      jerseyNumber: '85',
      position: 'FW(부주장)',
      year: '21학번',
      heightWeight: '180/72',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/21_jeonhyeokjoon.png',
      name: '전혁준',
      jerseyNumber: '72',
      position: 'FW',
      year: '21학번',
      heightWeight: '175/72',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/21_shindonghyeon.png',
      name: '신동현',
      jerseyNumber: '92',
      position: 'FW',
      year: '21학번',
      heightWeight: '182/77',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/21_janggaram.png',
      name: '장가람',
      jerseyNumber: '70',
      position: 'GK',
      year: '21학번',
      heightWeight: '185/87',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/22_leeseungjae.png',
      name: '이승재',
      jerseyNumber: '6',
      position: 'DF',
      year: '22학번',
      heightWeight: '182/83',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/22_moongeono.png',
      name: '문건오',
      jerseyNumber: '9',
      position: 'FW',
      year: '22학번',
      heightWeight: '174/74',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/22_hwangjaewoong.png',
      name: '황재웅',
      jerseyNumber: '17',
      position: 'FW',
      year: '22학번',
      heightWeight: '178/75',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/22_kimyongsoo.png',
      name: '김용수',
      jerseyNumber: '23',
      position: 'FW(부주장)',
      year: '22학번',
      heightWeight: '174/73',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/22_songjaewon.png',
      name: '송재원',
      jerseyNumber: '38',
      position: 'GK',
      year: '22학번',
      heightWeight: '174/70',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/23_imdonggyu.png',
      name: '임동규',
      jerseyNumber: '15',
      position: 'DF',
      year: '23학번',
      heightWeight: '190/82',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/23_gongyouchan.png',
      name: '공유찬',
      jerseyNumber: '18',
      position: 'DF',
      year: '23학번',
      heightWeight: '188/85',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/23_hongseungwoo.png',
      name: '홍승우',
      jerseyNumber: '55',
      position: 'DF',
      year: '23학번',
      heightWeight: '177/77',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/23_kimbeomseok.png',
      name: '김범석',
      jerseyNumber: '8',
      position: 'FW',
      year: '23학번',
      heightWeight: '185/83',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/23_kimdaon.png',
      name: '김다온',
      jerseyNumber: '11',
      position: 'FW',
      year: '23학번',
      heightWeight: '177/75',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/23_kimsihwan.png',
      name: '김시환',
      jerseyNumber: '13',
      position: 'FW',
      year: '23학번',
      heightWeight: '177/75',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/23_leejaehwan.png',
      name: '이재현',
      jerseyNumber: '66',
      position: 'FW',
      year: '23학번',
      heightWeight: '172/76',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/24_imeungyu.png',
      name: '임은규',
      jerseyNumber: '27',
      position: 'DF',
      year: '24학번',
      heightWeight: '180/75',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/24_jangjihyeon.png',
      name: '장지현',
      jerseyNumber: '78',
      position: 'DF',
      year: '24학번',
      heightWeight: '185/85',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/24_hwangseongho.png',
      name: '황성호',
      jerseyNumber: '4',
      position: 'FW',
      year: '24학번',
      heightWeight: '180/74',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/24_chaesoomin.png',
      name: '채수민',
      jerseyNumber: '19',
      position: 'FW',
      year: '24학번',
      heightWeight: '182/75',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/24_shinyoumin.png',
      name: '신윤민',
      jerseyNumber: '26',
      position: 'FW',
      year: '24학번',
      heightWeight: '186/84',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/24_gwonwoohyeon.png',
      name: '권우현',
      jerseyNumber: '67',
      position: 'FW',
      year: '24학번',
      heightWeight: '182/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/icehockey/24_oeunyul.png',
      name: '오은율',
      jerseyNumber: '1',
      position: 'GK',
      year: '24학번',
      heightWeight: '183/82',
    },
  ],
  football: [
    {
      image: '/image-proxy/analyze/profile/yonsei/football/21_hajaemin.png',
      name: '하재민',
      jerseyNumber: '14',
      position: 'CB',
      year: '21학번',
      heightWeight: '186/90',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/21_jangyoumin.png',
      name: '장유민',
      jerseyNumber: '16',
      position: 'LW, RWB',
      year: '21학번',
      heightWeight: '179/73',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/21_parkjisang.png',
      name: '박지상',
      jerseyNumber: '23',
      position: 'CM',
      year: '21학번',
      heightWeight: '176/68',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/22_parksiyoung.png',
      name: '박시영',
      jerseyNumber: '2',
      position: 'RWB',
      year: '22학번',
      heightWeight: '175/70',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/22_janghyeondo.png',
      name: '장현도',
      jerseyNumber: '7',
      position: 'LWB',
      year: '22학번',
      heightWeight: '170/66',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/22_parkgeonhee.png',
      name: '박건희',
      jerseyNumber: '9',
      position: 'RW',
      year: '22학번',
      heightWeight: '177/71',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/22_gangminjae.png',
      name: '강민재',
      jerseyNumber: '10',
      position: 'CF',
      year: '22학번',
      heightWeight: '184/80',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/22_jinuijoon.png',
      name: '진의준',
      jerseyNumber: '13',
      position: 'RCM, RW',
      year: '22학번',
      heightWeight: '173/70',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/22_hwangseungwoo.png',
      name: '황승우',
      jerseyNumber: '17',
      position: 'WF',
      year: '22학번',
      heightWeight: '177/75',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_gangminseo.png',
      name: '강민서',
      jerseyNumber: '4',
      position: 'CB',
      year: '23학번',
      heightWeight: '183/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_leeseungmin.png',
      name: '이승민',
      jerseyNumber: '6',
      position: 'CB',
      year: '23학번',
      heightWeight: '184/80',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_gwakminseok.png',
      name: '곽민석',
      jerseyNumber: '8',
      position: 'CDM, CM',
      year: '23학번',
      heightWeight: '179/73',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_janghyeonbin.png',
      name: '장현빈',
      jerseyNumber: '11',
      position: 'WF',
      year: '23학번',
      heightWeight: '179/73',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_janghamin.png',
      name: '장하민',
      jerseyNumber: '12',
      position: 'ST',
      year: '23학번',
      heightWeight: '178/71',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_gangjinyeob.png',
      name: '강진엽',
      jerseyNumber: '15',
      position: 'LB',
      year: '23학번',
      heightWeight: '179/73',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_choijiwoong.png',
      name: '최지웅',
      jerseyNumber: '18',
      position: 'CDM, CM',
      year: '23학번',
      heightWeight: '171/65',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/23_choigangseo.png',
      name: '최강서',
      jerseyNumber: '21',
      position: 'GK',
      year: '23학번',
      heightWeight: '187/78',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_kimhyeon.png',
      name: '김현',
      jerseyNumber: '1',
      position: 'GK',
      year: '24학번',
      heightWeight: '187/82',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_kimminwook.png',
      name: '김민욱',
      jerseyNumber: '3',
      position: 'CB',
      year: '24학번',
      heightWeight: '183/74',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_seonyejoon.png',
      name: '선예준',
      jerseyNumber: '5',
      position: 'CB',
      year: '24학번',
      heightWeight: '186/83',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_parkjoonheok.png',
      name: '박준혁',
      jerseyNumber: '19',
      position: 'CM',
      year: '24학번',
      heightWeight: '173/67',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_parkminjae.png',
      name: '박민재',
      jerseyNumber: '22',
      position: 'LB',
      year: '24학번',
      heightWeight: '174/68',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_leejaemin.png',
      name: '이재민',
      jerseyNumber: '27',
      position: 'ST',
      year: '24학번',
      heightWeight: '186/84',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_kimjeongin.png',
      name: '김정인',
      jerseyNumber: '28',
      position: 'WF',
      year: '24학번',
      heightWeight: '173/68',
    },
    {
      image: '/image-proxy/analyze/profile/yonsei/football/24_leejeongbin.png',
      name: '이정빈',
      jerseyNumber: '29',
      position: 'WF',
      year: '24학번',
      heightWeight: '179/73',
    },
  ],
};
